print("Ordem cronológica dos filmes da Marvel!")

print("1-Capitão Ameriaca: O primeiro vingador")
print("2-Homem de Ferro")
print("3-Homem de Ferro 2")
print("4-O Incrivel Hulk")
print("5-Thor")
print("6-Os Vingadores")
print("7-Thor: O Mundo Sombrio")
print("8-Homem de Ferro 3")
print("9-Capitão America: O Soldado Invernal")
print("10-Guardiões da Galáxia")
print("11-Guardiões da Galáxia Vol.2")
print("12-Vingadores:Era de Ultron")
print("13-Homem Formiga")
print("14-Capitão America: Guerra Civil")
print("15-Pantera Negra")
print("16-Homem Aranha: De Volta ao Lar")
print("17-Thor: Ragnarok")
print("18-Homem Formiga e a Vespa")
print("19-Vingadores: Guerra Infinita")
print("20-Vingadores: Ultimato")
